[package]
name = "show"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glow = "0.13.1"
glfw = "0.55.0"
image = "0.24.9"
